'use strict';
const API_URL='https://script.google.com/macros/s/AKfycbzztA7uR8e0unmEVYE_sL1m3p-HWveusfhV_pjJHDhGWvqGIAhfZB_2IeAHv8MHa_5b/exec';
const state={menu:[],cart:[],busy:false};
const $=id=>document.getElementById(id);
const escapeHtml=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const money=v=>Number(v||0).toLocaleString('en-US');
function setStatus(type,text){const el=$('api-status');if(el){el.className=`status-pill status-${type}`;el.innerHTML=text;}}
async function request(action,payload={},method='GET'){if(!API_URL||API_URL.includes('PASTE_GOOGLE'))throw new Error('API Google Apps Script belum dikonfigurasi.');const token=typeof getAuthToken==='function'?getAuthToken():'';const url=new URL(API_URL);const opt={method,mode:'cors',cache:'no-store'};if(method==='GET'){url.searchParams.set('action',action);url.searchParams.set('token',token);Object.entries(payload).forEach(([k,v])=>url.searchParams.set(k,v));}else{opt.headers={'Content-Type':'text/plain;charset=utf-8'};opt.body=JSON.stringify({action,...payload,token});}const response=await fetch(url,opt);if(!response.ok)throw new Error(`Server HTTP ${response.status}`);const result=await response.json();if(!result.ok){if(typeof requireLoginError==='function')requireLoginError(new Error(result.error||''));throw new Error(result.error||'API error')}return result.data;}
function setBusy(button,busy,label){if(!button)return;button.disabled=busy;button.innerHTML=busy?'<i class="fas fa-circle-notch fa-spin"></i> Memproses...':(label||'<i class="fas fa-receipt"></i> Proses &amp; Buat Struk');}
function renderMenu(){const grid=$('data-menu'),table=$('table-kelola-menu-body');if(!grid||!table)return;if(!state.menu.length){grid.innerHTML='<div class="empty-state"><i class="fas fa-utensils"></i><p>Belum ada menu.</p></div>';table.innerHTML='<tr><td colspan="3" class="empty-cell">Belum ada menu.</td></tr>';return;}grid.innerHTML=state.menu.map(i=>{const n=String(i?.[0]??''),p=Number(i?.[1])||0;return `<button class="menu-item" type="button" data-menu="${escapeHtml(n)}" data-price="${p}"><span class="menu-item-name">${escapeHtml(n)}</span><span class="menu-item-price">KHR ${money(p)}</span><span class="menu-add"><i class="fas fa-plus"></i> Tambah</span></button>`}).join('');table.innerHTML=state.menu.map(i=>{const n=String(i?.[0]??''),p=Number(i?.[1])||0;return `<tr><td>${escapeHtml(n)}</td><td>KHR ${money(p)}</td><td><button class="btn btn-sm btn-danger delete-menu" type="button" data-menu="${escapeHtml(n)}"><i class="fas fa-trash"></i></button></td></tr>`}).join('');}
function renderCart(){const box=$('cart-items');if(!box)return;let total=0;box.innerHTML=state.cart.length?state.cart.map((i,n)=>{const sub=i.qty*i.harga;total+=sub;return `<div class="cart-row"><div><strong>${escapeHtml(i.menu)}</strong><small>${escapeHtml(i.namaPelanggan)} · x${i.qty}</small></div><div class="cart-right"><span>KHR ${money(sub)}</span><div><button type="button" data-cart-index="${n}" data-delta="-1">−</button><button type="button" data-cart-index="${n}" data-delta="1">+</button></div></div></div>`}).join(''):'<div class="empty-state"><i class="fas fa-shopping-basket"></i><p>Belum ada item ditambahkan</p></div>';$('grand-total').textContent=money(total);}
function addToCart(menu,harga){const customer=($('nama-pelanggan')?.value||'').trim()||'Tamu Reguler';const x=state.cart.find(i=>i.menu===menu&&i.namaPelanggan===customer);if(x)x.qty++;else state.cart.push({namaPelanggan:customer,menu,harga:Number(harga)||0,qty:1});$('link-area')?.classList.add('hidden');renderCart();}
function resetCart(){state.cart=[];if($('nama-pelanggan'))$('nama-pelanggan').value='';renderCart();}
function changeQty(index,delta){const x=state.cart[index];if(!x)return;x.qty+=delta;if(x.qty<=0)state.cart.splice(index,1);renderCart();}
async function loadMenu(){const target=$('data-menu');if(target)target.innerHTML='<div class="empty-state"><i class="fas fa-circle-notch fa-spin"></i><p>Memuat menu...</p></div>';try{state.menu=await request('getMenu');renderMenu();setStatus('ok','<i class="fas fa-shield-check"></i> Admin Terverifikasi');}catch(err){if(target)target.innerHTML=`<div class="error-state"><i class="fas fa-triangle-exclamation"></i><p>${escapeHtml(err.message)}</p><small>Silakan login kembali jika sesi sudah berakhir.</small></div>`;setStatus('error','<i class="fas fa-circle-xmark"></i> Akses ditolak');}}
function renderHistory(rows){const body=$('history-table-body');if(!body)return;if(!Array.isArray(rows)||!rows.length){body.innerHTML='<tr><td colspan="7" class="empty-cell">Belum ada transaksi.</td></tr>';return;}body.innerHTML=rows.map(tx=>{const inv=String(tx.invoiceId||''),paid=tx.status==='Sudah Bayar',next=paid?'Belum Bayar':'Sudah Bayar';return `<tr><td><small>${escapeHtml(tx.waktu)}</small></td><td><a class="invoice-link" href="struk.html?id=${encodeURIComponent(inv)}" target="_blank" rel="noopener"><span class="invoice-badge">${escapeHtml(inv)}</span></a></td><td><strong>${escapeHtml(tx.nama)}</strong></td><td>${escapeHtml(tx.pesanan)}</td><td><strong>KHR ${money(tx.total)}</strong></td><td><span class="badge ${paid?'badge-paid':'badge-unpaid'}">${escapeHtml(tx.status)}</span></td><td><button class="btn btn-sm ${paid?'btn-warning':'btn-success'} status-btn" data-invoice="${escapeHtml(inv)}" data-status="${escapeHtml(next)}" type="button">${paid?'Set Belum':'Lunas'}</button></td></tr>`}).join('');}
async function loadHistory(){const body=$('history-table-body');if(body)body.innerHTML='<tr><td colspan="7" class="empty-cell">Memuat laporan...</td></tr>';try{renderHistory(await request('getHistory'));}catch(err){if(body)body.innerHTML=`<tr><td colspan="7" class="empty-cell error-text">${escapeHtml(err.message)}</td></tr>`;}}
function switchTab(name,button){document.querySelectorAll('.tab-view').forEach(e=>e.classList.add('hidden'));document.querySelectorAll('.nav-tab').forEach(e=>e.classList.remove('active'));$(`tab-${name}`)?.classList.remove('hidden');button?.classList.add('active');if(name==='history')loadHistory();if(name==='kelola-menu')renderMenu();if(name==='finance'&&typeof initFinance==='function')initFinance();}
async function bayar(){if(state.busy)return;if(!state.cart.length){alert('Keranjang masih kosong.');return;}state.busy=true;const b=$('pay-btn');setBusy(b,true);try{const items=state.cart.map(i=>({nama:i.namaPelanggan,pesanan:`${i.menu} (x${i.qty})`,total:i.qty*i.harga}));const r=await request('saveTransaction',{items,statusBayar:$('status-pembayaran')?.value||'Sudah Bayar'},'POST'),link=r?.link||'';$('invoice-link').value=link;$('open-link').href=link||'#';$('wa-link').href=`https://wa.me/?text=${encodeURIComponent(`Halo, ini tagihan pesanan Anda di KUDAJITU AMAZON.\n\nCek rincian pesanan di: ${link}`)}`;$('link-area').classList.remove('hidden');state.cart=[];renderCart();if(link)window.open(link,'_blank','noopener');}catch(err){alert(`Transaksi gagal: ${err.message}`);}finally{state.busy=false;setBusy(b,false);}}
async function updateStatus(invoiceId,status){try{renderHistory(await request('updateStatus',{invoiceId,statusBaru:status},'POST'));}catch(err){alert(`Gagal mengubah status: ${err.message}`);}}
async function addMenu(){const namaMenu=($('input-nama-menu')?.value||'').trim(),hargaMenu=($('input-harga-menu')?.value||'').trim();if(!namaMenu||!hargaMenu||Number(hargaMenu)<0){alert('Nama dan harga menu harus valid.');return;}try{state.menu=await request('addMenu',{namaMenu,hargaMenu},'POST');renderMenu();$('input-nama-menu').value='';$('input-harga-menu').value='';}catch(err){alert(`Gagal menambah menu: ${err.message}`);}}
async function deleteMenu(namaMenu){if(!confirm(`Hapus menu "${namaMenu}"?`))return;try{state.menu=await request('deleteMenu',{namaMenu},'POST');renderMenu();}catch(err){alert(`Gagal menghapus menu: ${err.message}`);}}
async function copyLink(){const input=$('invoice-link');if(!input?.value)return;try{await navigator.clipboard.writeText(input.value);alert('Link disalin.');}catch(_){input.select();document.execCommand('copy');alert('Link disalin.');}}
document.addEventListener('click',e=>{const m=e.target.closest('.menu-item');if(m)return addToCart(m.dataset.menu,Number(m.dataset.price));const q=e.target.closest('[data-cart-index]');if(q)return changeQty(Number(q.dataset.cartIndex),Number(q.dataset.delta));const d=e.target.closest('.delete-menu');if(d)return deleteMenu(d.dataset.menu);const s=e.target.closest('.status-btn');if(s)return updateStatus(s.dataset.invoice,s.dataset.status);});
window.switchTab=switchTab;window.loadMenu=loadMenu;window.loadHistory=loadHistory;window.bayar=bayar;window.resetCart=resetCart;window.tambahMenu=addMenu;window.copyLink=copyLink;window.addToCart=addToCart;window.addEventListener('error',e=>{console.error(e.error||e.message);setStatus('error','<i class="fas fa-circle-xmark"></i> JS Error');});window.addEventListener('DOMContentLoaded',()=>{renderCart();if(typeof initAuth==='function')initAuth();});