const AUTH_KEY='kudajitu_admin_token';
function getAuthToken(){return sessionStorage.getItem(AUTH_KEY)||''}
function setAuthToken(token){if(token)sessionStorage.setItem(AUTH_KEY,token);else sessionStorage.removeItem(AUTH_KEY)}
function clearAuthToken(){sessionStorage.removeItem(AUTH_KEY)}
function showLogin(message=''){document.getElementById('login-screen')?.classList.remove('hidden');document.getElementById('admin-ui')?.classList.add('hidden');const e=document.getElementById('login-error');if(e)e.textContent=message}
function hideLogin(){document.getElementById('login-screen')?.classList.add('hidden');document.getElementById('admin-ui')?.classList.remove('hidden');document.getElementById('login-user')?.blur();document.getElementById('login-pass')?.blur()}
async function adminLogin(event){if(event)event.preventDefault();const username=(document.getElementById('login-user')?.value||'').trim(),password=document.getElementById('login-pass')?.value||'',button=document.getElementById('login-btn'),error=document.getElementById('login-error');if(!username||!password){showLogin('Username dan password wajib diisi.');return false}if(typeof API_URL==='undefined'||!API_URL){showLogin('API login belum dikonfigurasi.');return false}if(button){button.disabled=true;button.innerHTML='<i class="fas fa-circle-notch fa-spin"></i> Memverifikasi...'}if(error)error.textContent='';try{const r=await fetch(API_URL,{method:'POST',mode:'cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'login',username,password})});const text=await r.text();let j;try{j=JSON.parse(text)}catch(_){throw new Error(`Respons server tidak valid (HTTP ${r.status}). Pastikan deployment Apps Script menggunakan versi terbaru.`)}if(!r.ok)throw new Error(`Server HTTP ${r.status}`);if(!j.ok)throw new Error(j.error||'Username atau password salah.');if(!j.data?.token)throw new Error('Login berhasil tetapi token sesi tidak diterima.');setAuthToken(j.data.token);hideLogin();if(typeof setStatus==='function')setStatus('ok','<i class="fas fa-shield-check"></i> Admin Terverifikasi');if(typeof loadMenu==='function')await loadMenu();return true}catch(e){clearAuthToken();showLogin(e.message||'Login gagal.');return false}finally{if(button){button.disabled=false;button.innerHTML='<i class="fas fa-right-to-bracket"></i> Masuk'}}}
async function adminLogout(){const token=getAuthToken();try{if(token&&typeof API_URL!=='undefined')await fetch(API_URL,{method:'POST',mode:'cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'logout',token})})}catch(_){}clearAuthToken();showLogin('Anda telah keluar.')}
function requireLoginError(e){if(/login|sesi|token|otorisasi|unauthor/i.test(String(e?.message||''))){clearAuthToken();showLogin('Sesi admin tidak valid atau sudah berakhir. Silakan login kembali.');return true}return false}
function initAuth(){const pass=document.getElementById('login-pass'),user=document.getElementById('login-user');if(pass&&!pass.dataset.authBound){pass.dataset.authBound='1';pass.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();adminLogin(e)}})}if(user&&!user.dataset.authBound){user.dataset.authBound='1';user.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();pass?.focus()}})}if(getAuthToken()){hideLogin();if(typeof loadMenu==='function')loadMenu()}else showLogin('')}
window.getAuthToken=getAuthToken;window.adminLogin=adminLogin;window.adminLogout=adminLogout;window.initAuth=initAuth;window.requireLoginError=requireLoginError;