const AUTH_KEY='kudajitu_admin_token';
function getAuthToken(){return sessionStorage.getItem(AUTH_KEY)||''}
function setAuthToken(token){sessionStorage.setItem(AUTH_KEY,token||'')}
function clearAuthToken(){sessionStorage.removeItem(AUTH_KEY)}
function showLogin(message=''){document.getElementById('login-screen')?.classList.remove('hidden');document.getElementById('admin-ui')?.classList.add('hidden');const e=document.getElementById('login-error');if(e)e.textContent=message}
function hideLogin(){document.getElementById('login-screen')?.classList.add('hidden');document.getElementById('admin-ui')?.classList.remove('hidden');document.getElementById('login-user')?.blur();document.getElementById('login-pass')?.blur()}
async function adminLogin(){const username=document.getElementById('login-user')?.value.trim()||'',password=document.getElementById('login-pass')?.value||'',button=document.getElementById('login-btn');if(!username||!password){showLogin('Username dan password wajib diisi.');return}button.disabled=true;button.innerHTML='<i class="fas fa-circle-notch fa-spin"></i> Masuk...';try{const url=new URL(API_URL),r=await fetch(url,{method:'POST',mode:'cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'login',username,password})}),j=await r.json();if(!j.ok)throw new Error(j.error||'Login gagal');setAuthToken(j.data.token);hideLogin();if(typeof loadMenu==='function')loadMenu();if(typeof setStatus==='function')setStatus('ok','<i class="fas fa-shield-check"></i> Admin Terverifikasi')}catch(e){showLogin(e.message)}finally{button.disabled=false;button.innerHTML='<i class="fas fa-right-to-bracket"></i> Masuk'}}
async function adminLogout(){const token=getAuthToken();try{await fetch(API_URL,{method:'POST',mode:'cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'logout',token})})}catch(_){}clearAuthToken();showLogin('Anda telah keluar.')}
function requireLoginError(e){if(/login|sesi/i.test(String(e?.message||''))){clearAuthToken();showLogin('Sesi berakhir. Silakan login kembali.');return true}return false}
function initAuth(){if(getAuthToken()){hideLogin();if(typeof loadMenu==='function')loadMenu()}else showLogin();document.getElementById('login-pass')?.addEventListener('keydown',e=>{if(e.key==='Enter')adminLogin()})}
window.getAuthToken=getAuthToken;window.adminLogin=adminLogin;window.adminLogout=adminLogout;window.initAuth=initAuth;window.requireLoginError=requireLoginError;