const SPREADSHEET_ID = "1ZRmlqBINoh9kNgSq9o47Ogi7TDZPV2ykNFdlLU5BmYg";
const FRONTEND_URL = "https://kudajitu-pos.pages.dev/struk.html";
const FINANCE_HEADERS=['ID','Tanggal','Jenis','Kategori','Keterangan','Nominal KHR','Metode','Dibuat Pada'];
const FINANCE_CATEGORIES=['Makanan','Tempat Tinggal','Transportasi','Belanja','Internet/Pulsa','Hiburan','Kesehatan','Kebutuhan Kerja','Tagihan','Gaji/Pemasukan','Lainnya'];
function getSheet(namaSheet){if(SPREADSHEET_ID)return SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(namaSheet);return SpreadsheetApp.getActiveSpreadsheet().getSheetByName(namaSheet);}
function ensureFinanceSheet(){const ss=SpreadsheetApp.openById(SPREADSHEET_ID);let s=ss.getSheetByName('Keuangan');if(!s){s=ss.insertSheet('Keuangan');s.getRange(1,1,1,FINANCE_HEADERS.length).setValues([FINANCE_HEADERS]);s.setFrozenRows(1);s.getRange(1,1,1,FINANCE_HEADERS.length).setFontWeight('bold');}else if(s.getLastColumn()<FINANCE_HEADERS.length){s.getRange(1,1,1,FINANCE_HEADERS.length).setValues([FINANCE_HEADERS]);}return s;}
function jsonResponse(payload){return ContentService.createTextOutput(JSON.stringify(payload)).setMimeType(ContentService.MimeType.JSON);}
function doGet(e){const p=e&&e.parameter?e.parameter:{};try{if(p.action==='getMenu')return jsonResponse({ok:true,data:getMenuData()});if(p.action==='getHistory')return jsonResponse({ok:true,data:getHistoryData()});if(p.action==='getInvoice')return jsonResponse({ok:true,data:getInvoiceData(p.id||'')});if(p.action==='getFinance')return jsonResponse({ok:true,data:getFinanceData(p.month||'')});return jsonResponse({ok:true,data:{service:'KUDAJITU POS API'}});}catch(err){return jsonResponse({ok:false,error:err.message||String(err)});}}
function doPost(e){let body;try{body=JSON.parse((e&&e.postData&&e.postData.contents)||'{}');}catch(err){return jsonResponse({ok:false,error:'JSON tidak valid.'});}try{let data;if(body.action==='saveTransaction')data=simpanTransaksi(body.items||[],body.statusBayar);else if(body.action==='addMenu')data=tambahMenuBaru(body.namaMenu,body.hargaMenu);else if(body.action==='deleteMenu')data=hapusMenuBerdasarkanNama(body.namaMenu);else if(body.action==='updateStatus')data=updateStatusTransaksi(body.invoiceId,body.statusBaru);else if(body.action==='saveFinance')data=saveFinanceRecord(body);else if(body.action==='deleteFinance')data=deleteFinanceRecord(body.id);else return jsonResponse({ok:false,error:'Action tidak dikenali.'});return jsonResponse({ok:true,data:data});}catch(err){return jsonResponse({ok:false,error:err.message||String(err)});}}
function getMenuData(){const sheet=getSheet('Menu');if(!sheet)throw new Error('Sheet "Menu" tidak ditemukan!');const data=sheet.getDataRange().getValues();if(data.length<=1)return[];data.shift();return data.filter(row=>row[0]!=='');}
function tambahMenuBaru(namaMenu,hargaMenu){if(!namaMenu)throw new Error('Nama menu wajib diisi.');if(hargaMenu===''||hargaMenu===null||isNaN(Number(hargaMenu)))throw new Error('Harga menu tidak valid.');const sheet=getSheet('Menu');if(!sheet)throw new Error('Sheet "Menu" tidak ditemukan!');sheet.appendRow([namaMenu,Number(hargaMenu)]);return getMenuData();}
function hapusMenuBerdasarkanNama(namaMenu){const sheet=getSheet('Menu');if(!sheet)throw new Error('Sheet "Menu" tidak ditemukan!');const data=sheet.getDataRange().getValues();for(let i=data.length-1;i>=1;i--)if(String(data[i][0])===String(namaMenu)){sheet.deleteRow(i+1);break;}return getMenuData();}
function simpanTransaksi(dataTransaksi,statusBayar){const sheet=getSheet('Transaksi');if(!sheet)throw new Error('Sheet "Transaksi" tidak ditemukan!');if(!Array.isArray(dataTransaksi)||dataTransaksi.length===0)throw new Error('Tidak ada item transaksi.');const waktu=new Date(),invoiceId='INV'+waktu.getTime().toString().slice(-6),status=statusBayar||'Sudah Bayar';dataTransaksi.forEach(tx=>sheet.appendRow([waktu,tx.nama,tx.pesanan,Number(tx.total)||0,invoiceId,status]));return{id:invoiceId,invoiceId:invoiceId,link:FRONTEND_URL+'?id='+encodeURIComponent(invoiceId)};}
function updateStatusTransaksi(invoiceId,statusBaru){const sheet=getSheet('Transaksi');if(!sheet)throw new Error('Sheet "Transaksi" tidak ditemukan!');const data=sheet.getDataRange().getValues();for(let i=1;i<data.length;i++)if(String(data[i][4])===String(invoiceId))sheet.getRange(i+1,6).setValue(statusBaru);return getHistoryData();}
function getInvoiceData(invoiceId){const sheet=getSheet('Transaksi');if(!sheet)throw new Error('Sheet "Transaksi" tidak ditemukan!');const data=sheet.getDataRange().getValues(),result=[];for(let i=1;i<data.length;i++)if(String(data[i][4])===String(invoiceId)){const tgl=data[i][0],waktu=tgl instanceof Date?Utilities.formatDate(tgl,Session.getScriptTimeZone(),'dd/MM/yyyy HH:mm'):String(tgl||'');result.push({waktu:waktu,nama:data[i][1],pesanan:data[i][2],total:Number(data[i][3])||0,status:data[i][5]||'Sudah Bayar'});}return result;}
function getHistoryData(){const sheet=getSheet('Transaksi');if(!sheet)throw new Error('Sheet "Transaksi" tidak ditemukan!');const data=sheet.getDataRange().getValues();if(data.length<=1)return[];data.shift();return data.map(row=>{const tgl=row[0],waktu=tgl instanceof Date?Utilities.formatDate(tgl,Session.getScriptTimeZone(),'dd/MM/yyyy HH:mm'):String(tgl||'');return{waktu:waktu,nama:row[1],pesanan:row[2],total:Number(row[3])||0,invoiceId:row[4],status:row[5]||'Sudah Bayar'};}).reverse();}
function normalizeFinanceDate(v){if(v instanceof Date)return Utilities.formatDate(v,Session.getScriptTimeZone(),'yyyy-MM-dd');const s=String(v||'');return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:sliceDate(new Date());}
function sliceDate(d){return Utilities.formatDate(d,Session.getScriptTimeZone(),'yyyy-MM-dd');}
function saveFinanceRecord(b){const s=ensureFinanceSheet(),tanggal=normalizeFinanceDate(b.tanggal),jenis=String(b.jenis||'Pengeluaran'),kategori=String(b.kategori||'Lainnya'),keterangan=String(b.keterangan||'').trim(),nominal=Number(b.nominal),metode=String(b.metode||'Cash');if(!['Pemasukan','Pengeluaran'].includes(jenis))throw new Error('Jenis transaksi tidak valid.');if(!keterangan)throw new Error('Keterangan wajib diisi.');if(!isFinite(nominal)||nominal<=0)throw new Error('Nominal harus lebih dari 0.');const id='FIN'+Date.now().toString().slice(-9);s.appendRow([id,tanggal,jenis,kategori,keterangan,nominal,metode,new Date()]);return{id:id};}
function deleteFinanceRecord(id){const s=ensureFinanceSheet(),data=s.getDataRange().getValues();for(let i=data.length-1;i>=1;i--)if(String(data[i][0])===String(id)){s.deleteRow(i+1);return true;}throw new Error('Catatan tidak ditemukan.');}
function getFinanceData(month){const s=ensureFinanceSheet(),data=s.getDataRange().getValues();const target=/^\d{4}-\d{2}$/.test(String(month||''))?String(month):Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyy-MM');let income=0,expense=0,rows=[];for(let i=1;i<data.length;i++){const r=data[i],tanggal=normalizeFinanceDate(r[1]);if(tanggal.slice(0,7)!==target)continue;const nominal=Number(r[5])||0;if(String(r[2])==='Pemasukan')income+=nominal;else expense+=nominal;rows.push({id:String(r[0]),tanggal:tanggal,jenis:String(r[2]||'Pengeluaran'),kategori:String(r[3]||'Lainnya'),keterangan:String(r[4]||''),nominal:nominal,metode:String(r[6]||'Cash')});}rows.reverse();return{currency:'KHR',month:target,summary:{income:income,expense:expense,balance:income-expense,count:rows.length},transactions:rows,categories:FINANCE_CATEGORIES};}
