const SPREADSHEET_ID = "1ZRmlqBINoh9kNgSq9o47Ogi7TDZPV2ykNFdlLU5BmYg";
const FRONTEND_URL = "https://kudajitu-pos.pages.dev/";

function getSheet(namaSheet) {
  if (SPREADSHEET_ID) return SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(namaSheet);
  return SpreadsheetApp.getActiveSpreadsheet().getSheetByName(namaSheet);
}
function jsonResponse(payload) { return ContentService.createTextOutput(JSON.stringify(payload)).setMimeType(ContentService.MimeType.JSON); }
function doGet(e) { const p=e&&e.parameter?e.parameter:{}; try { if(p.action==='getMenu')return jsonResponse({ok:true,data:getMenuData()}); if(p.action==='getHistory')return jsonResponse({ok:true,data:getHistoryData()}); if(p.action==='getInvoice')return jsonResponse({ok:true,data:getInvoiceData(p.id||'')}); return jsonResponse({ok:true,data:{service:'KUDAJITU POS API'}}); } catch(err){return jsonResponse({ok:false,error:err.message||String(err)});} }
function doPost(e) { let body; try{body=JSON.parse((e&&e.postData&&e.postData.contents)||'{}');}catch(err){return jsonResponse({ok:false,error:'JSON tidak valid.'});} try{let data;if(body.action==='saveTransaction')data=simpanTransaksi(body.items||[],body.statusBayar);else if(body.action==='addMenu')data=tambahMenuBaru(body.namaMenu,body.hargaMenu);else if(body.action==='deleteMenu')data=hapusMenuBerdasarkanNama(body.namaMenu);else if(body.action==='updateStatus')data=updateStatusTransaksi(body.invoiceId,body.statusBaru);else return jsonResponse({ok:false,error:'Action tidak dikenali.'});return jsonResponse({ok:true,data:data});}catch(err){return jsonResponse({ok:false,error:err.message||String(err)});} }
function getMenuData(){const sheet=getSheet('Menu');if(!sheet)throw new Error('Sheet "Menu" tidak ditemukan!');const data=sheet.getDataRange().getValues();if(data.length<=1)return[];data.shift();return data.filter(row=>row[0]!=='');}
function tambahMenuBaru(namaMenu,hargaMenu){if(!namaMenu)throw new Error('Nama menu wajib diisi.');if(hargaMenu===''||hargaMenu===null||isNaN(Number(hargaMenu)))throw new Error('Harga menu tidak valid.');const sheet=getSheet('Menu');if(!sheet)throw new Error('Sheet "Menu" tidak ditemukan!');sheet.appendRow([namaMenu,Number(hargaMenu)]);return getMenuData();}
function hapusMenuBerdasarkanNama(namaMenu){const sheet=getSheet('Menu');if(!sheet)throw new Error('Sheet "Menu" tidak ditemukan!');const data=sheet.getDataRange().getValues();for(let i=data.length-1;i>=1;i--)if(String(data[i][0])===String(namaMenu)){sheet.deleteRow(i+1);break;}return getMenuData();}
function simpanTransaksi(dataTransaksi,statusBayar){const sheet=getSheet('Transaksi');if(!sheet)throw new Error('Sheet "Transaksi" tidak ditemukan!');if(!Array.isArray(dataTransaksi)||dataTransaksi.length===0)throw new Error('Tidak ada item transaksi.');const waktu=new Date(),invoiceId='INV'+waktu.getTime().toString().slice(-6),status=statusBayar||'Sudah Bayar';dataTransaksi.forEach(tx=>sheet.appendRow([waktu,tx.nama,tx.pesanan,Number(tx.total)||0,invoiceId,status]));return{id:invoiceId,invoiceId:invoiceId,link:FRONTEND_URL+'?id='+encodeURIComponent(invoiceId)};}
function updateStatusTransaksi(invoiceId,statusBaru){const sheet=getSheet('Transaksi');if(!sheet)throw new Error('Sheet "Transaksi" tidak ditemukan!');const data=sheet.getDataRange().getValues();for(let i=1;i<data.length;i++)if(String(data[i][4])===String(invoiceId))sheet.getRange(i+1,6).setValue(statusBaru);return getHistoryData();}
function getInvoiceData(invoiceId){const sheet=getSheet('Transaksi');if(!sheet)throw new Error('Sheet "Transaksi" tidak ditemukan!');const data=sheet.getDataRange().getValues(),result=[];for(let i=1;i<data.length;i++)if(String(data[i][4])===String(invoiceId)){const tgl=data[i][0],waktu=tgl instanceof Date?Utilities.formatDate(tgl,Session.getScriptTimeZone(),'dd/MM/yyyy HH:mm'):String(tgl||'');result.push({waktu:waktu,nama:data[i][1],pesanan:data[i][2],total:Number(data[i][3])||0,status:data[i][5]||'Sudah Bayar'});}return result;}
function getHistoryData(){const sheet=getSheet('Transaksi');if(!sheet)throw new Error('Sheet "Transaksi" tidak ditemukan!');const data=sheet.getDataRange().getValues();if(data.length<=1)return[];data.shift();return data.map(row=>{const tgl=row[0],waktu=tgl instanceof Date?Utilities.formatDate(tgl,Session.getScriptTimeZone(),'dd/MM/yyyy HH:mm'):String(tgl||'');return{waktu:waktu,nama:row[1],pesanan:row[2],total:Number(row[3])||0,invoiceId:row[4],status:row[5]||'Sudah Bayar'};}).reverse();}
