const SPREADSHEET_ID="1ZRmlqBINoh9kNgSq9o47Ogi7TDZPV2ykNFdlLU5BmYg";
const FRONTEND_URL="https://kudajitu-pos.pages.dev/struk.html";
const FINANCE_HEADERS=['ID','Tanggal','Jenis','Kategori','Keterangan','Nominal KHR','Metode','Dibuat Pada'];
const FINANCE_CATEGORIES=['Makanan','Tempat Tinggal','Transportasi','Belanja','Internet/Pulsa','Hiburan','Kesehatan','Kebutuhan Kerja','Tagihan','Gaji/Pemasukan','Penyesuaian Saldo','Lainnya'];
const DEFAULT_ACCOUNTS=['Cash','ABA','AC Bank','Wing','Pi Pay'];
const AUTH_TOKEN_TTL=21600;
function getSheet(n){if(SPREADSHEET_ID)return SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(n);return SpreadsheetApp.getActiveSpreadsheet().getSheetByName(n)}
function ensureSheet(n,h){const ss=SpreadsheetApp.openById(SPREADSHEET_ID);let s=ss.getSheetByName(n);if(!s){s=ss.insertSheet(n);s.getRange(1,1,1,h.length).setValues([h]);s.setFrozenRows(1);s.getRange(1,1,1,h.length).setFontWeight('bold')}return s}
function ensureFinanceSheet(){return ensureSheet('Keuangan',FINANCE_HEADERS)}
function ensureAccountSheet(){const s=ensureSheet('Akun',['ID','Nama Akun','Saldo Awal KHR','Aktif','Dibuat Pada']);if(s.getLastRow()===1)DEFAULT_ACCOUNTS.forEach((n,i)=>s.appendRow(['ACC'+(i+1),n,0,true,new Date()]));return s}
function ensureTransferSheet(){return ensureSheet('Transfer',['ID','Tanggal','Dari','Ke','Nominal KHR','Catatan','Dibuat Pada'])}
function ensureBudgetSheet(){return ensureSheet('Budget',['Bulan','Kategori','Budget KHR','Dibuat Pada'])}
function jsonResponse(p){return ContentService.createTextOutput(JSON.stringify(p)).setMimeType(ContentService.MimeType.JSON)}
function sha256(v){const bytes=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(v),Utilities.Charset.UTF_8);return bytes.map(b=>(b<0?b+256:b).toString(16).padStart(2,'0')).join('')}
function getAdminPasswordHash(){return PropertiesService.getScriptProperties().getProperty('ADMIN_PASSWORD_HASH')||''}
function issueToken(){const token=Utilities.getUuid()+'-'+Utilities.getUuid();CacheService.getScriptCache().put('AUTH_'+token,'admin',AUTH_TOKEN_TTL);return token}
function requireAuth(token){if(!token)throw new Error('Sesi admin belum login.');if(CacheService.getScriptCache().get('AUTH_'+token)!=='admin')throw new Error('Sesi login sudah berakhir. Silakan login kembali.')}
function loginAdmin(username,password){const u=String(username||'').trim(),p=String(password||'');const hash=getAdminPasswordHash();if(!hash)throw new Error('Login belum dikonfigurasi. Tambahkan ADMIN_PASSWORD_HASH di Script Properties.');if(u!=='admin'||sha256(p)!==hash)throw new Error('Username atau password salah.');return{token:issueToken(),expiresIn:AUTH_TOKEN_TTL,user:'Admin Pusat'}}
function changeAdminPassword(token,currentPassword,newPassword){requireAuth(token);const current=String(currentPassword||''),next=String(newPassword||'');if(!current||!next)throw new Error('Password lama dan password baru wajib diisi.');if(next.length<8)throw new Error('Password baru minimal 8 karakter.');if(sha256(current)!==getAdminPasswordHash())throw new Error('Password lama salah.');if(current===next)throw new Error('Password baru harus berbeda dari password lama.');PropertiesService.getScriptProperties().setProperty('ADMIN_PASSWORD_HASH',sha256(next));CacheService.getScriptCache().remove('AUTH_'+token);return{changed:true,loggedOut:true,message:'Password berhasil diubah. Silakan login kembali.'}}
function logoutAdmin(token){if(token)CacheService.getScriptCache().remove('AUTH_'+token);return true}
function doGet(e){const p=e&&e.parameter?e.parameter:{};try{if(p.action==='login')return jsonResponse({ok:true,data:loginAdmin(p.username,p.password)});if(p.action==='getInvoice')return jsonResponse({ok:true,data:getInvoiceData(p.id||'')});requireAuth(p.token);if(p.action==='getMenu')return jsonResponse({ok:true,data:getMenuData()});if(p.action==='getHistory')return jsonResponse({ok:true,data:getHistoryData()});if(p.action==='getFinance')return jsonResponse({ok:true,data:getFinanceData(p.month||'')});if(p.action==='exportFinance')return jsonResponse({ok:true,data:exportFinanceData(p.month||'')});return jsonResponse({ok:true,data:{service:'KUDAJITU POS API',authenticated:true}})}catch(err){return jsonResponse({ok:false,error:err.message||String(err)})}}
function doPost(e){let b;try{b=JSON.parse((e&&e.postData&&e.postData.contents)||'{}')}catch(err){return jsonResponse({ok:false,error:'JSON tidak valid.'})}try{if(b.action==='login')return jsonResponse({ok:true,data:loginAdmin(b.username,b.password)});if(b.action==='logout')return jsonResponse({ok:true,data:logoutAdmin(b.token)});if(b.action==='changePassword')return jsonResponse({ok:true,data:changeAdminPassword(b.token,b.currentPassword,b.newPassword)});requireAuth(b.token);let d;if(b.action==='saveTransaction')d=simpanTransaksi(b.items||[],b.statusBayar);else if(b.action==='addMenu')d=tambahMenuBaru(b.namaMenu,b.hargaMenu);else if(b.action==='deleteMenu')d=hapusMenuBerdasarkanNama(b.namaMenu);else if(b.action==='updateStatus')d=updateStatusTransaksi(b.invoiceId,b.statusBaru);else if(b.action==='saveFinance')d=saveFinanceRecord(b);else if(b.action==='deleteFinance')d=deleteFinanceRecord(b.id);else if(b.action==='saveAccount')d=saveAccount(b);else if(b.action==='saveTransfer')d=saveTransfer(b);else if(b.action==='saveBudget')d=saveBudget(b);else if(b.action==='reconcileAccount')d=reconcileAccount(b);else return jsonResponse({ok:false,error:'Action tidak dikenali.'});return jsonResponse({ok:true,data:d})}catch(err){return jsonResponse({ok:false,error:err.message||String(err)})}}
function getMenuData(){const s=getSheet('Menu');if(!s)throw new Error('Sheet "Menu" tidak ditemukan!');const d=s.getDataRange().getValues();if(d.length<=1)return[];d.shift();return d.filter(r=>r[0]!=='')}
function tambahMenuBaru(n,h){if(!n)throw new Error('Nama menu wajib diisi.');if(h===''||h===null||isNaN(Number(h)))throw new Error('Harga menu tidak valid.');const s=getSheet('Menu');if(!s)throw new Error('Sheet "Menu" tidak ditemukan!');s.appendRow([n,Number(h)]);return getMenuData()}
function hapusMenuBerdasarkanNama(n){const s=getSheet('Menu');if(!s)throw new Error('Sheet "Menu" tidak ditemukan!');const d=s.getDataRange().getValues();for(let i=d.length-1;i>=1;i--)if(String(d[i][0])===String(n)){s.deleteRow(i+1);break}return getMenuData()}
function simpanTransaksi(items,status){const s=getSheet('Transaksi');if(!s)throw new Error('Sheet "Transaksi" tidak ditemukan!');if(!Array.isArray(items)||!items.length)throw new Error('Tidak ada item transaksi.');const w=new Date(),inv='INV'+w.getTime().toString().slice(-6),st=status||'Sudah Bayar';items.forEach(x=>s.appendRow([w,x.nama,x.pesanan,Number(x.total)||0,inv,st]));return{id:inv,invoiceId:inv,link:FRONTEND_URL+'?id='+encodeURIComponent(inv)}}
function updateStatusTransaksi(inv,st){const s=getSheet('Transaksi');if(!s)throw new Error('Sheet "Transaksi" tidak ditemukan!');const d=s.getDataRange().getValues();for(let i=1;i<d.length;i++)if(String(d[i][4])===String(inv))s.getRange(i+1,6).setValue(st);return getHistoryData()}
function getInvoiceData(inv){const s=getSheet('Transaksi');if(!s)throw new Error('Sheet "Transaksi" tidak ditemukan!');const d=s.getDataRange().getValues(),out=[];for(let i=1;i<d.length;i++)if(String(d[i][4])===String(inv)){const t=d[i][0];out.push({waktu:t instanceof Date?Utilities.formatDate(t,Session.getScriptTimeZone(),'dd/MM/yyyy HH:mm'):String(t||''),nama:d[i][1],pesanan:d[i][2],total:Number(d[i][3])||0,status:d[i][5]||'Sudah Bayar'})}return out}
function getHistoryData(){const s=getSheet('Transaksi');if(!s)throw new Error('Sheet "Transaksi" tidak ditemukan!');const d=s.getDataRange().getValues();if(d.length<=1)return[];d.shift();return d.map(r=>({waktu:r[0] instanceof Date?Utilities.formatDate(r[0],Session.getScriptTimeZone(),'dd/MM/yyyy HH:mm'):String(r[0]||''),nama:r[1],pesanan:r[2],total:Number(r[3])||0,invoiceId:r[4],status:r[5]||'Sudah Bayar'})).reverse()}
function normalizeFinanceDate(v){if(v instanceof Date)return Utilities.formatDate(v,Session.getScriptTimeZone(),'yyyy-MM-dd');const x=String(v||'');return /^\d{4}-\d{2}-\d{2}$/.test(x)?x:Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyy-MM-dd')}
function saveFinanceRecord(b){const s=ensureFinanceSheet(),t=normalizeFinanceDate(b.tanggal),j=String(b.jenis||'Pengeluaran'),k=String(b.kategori||'Lainnya'),n=String(b.keterangan||'').trim(),a=Number(b.nominal),m=String(b.metode||'Cash');if(!['Pemasukan','Pengeluaran'].includes(j))throw new Error('Jenis transaksi tidak valid.');if(!n)throw new Error('Keterangan wajib diisi.');if(!isFinite(a)||a<=0)throw new Error('Nominal harus lebih dari 0.');s.appendRow(['FIN'+Date.now().toString().slice(-9),t,j,k,n,a,m,new Date()]);return true}
function deleteFinanceRecord(id){const s=ensureFinanceSheet(),d=s.getDataRange().getValues();for(let i=d.length-1;i>=1;i--)if(String(d[i][0])===String(id)){s.deleteRow(i+1);return true}throw new Error('Catatan tidak ditemukan.')}
function saveAccount(b){const n=String(b.nama||'').trim(),saldo=Number(b.saldoAwal)||0;if(!n)throw new Error('Nama akun wajib diisi.');const s=ensureAccountSheet(),d=s.getDataRange().getValues();for(let i=1;i<d.length;i++)if(String(d[i][1]).trim().toLowerCase()===n.toLowerCase())throw new Error(`Akun "${n}" sudah ada.`);s.appendRow(['ACC'+Date.now().toString().slice(-8),n,saldo,true,new Date()]);return getAccountData()}
function saveTransfer(b){const t=normalizeFinanceDate(b.tanggal),d=String(b.dari||''),k=String(b.ke||''),a=Number(b.nominal),c=String(b.catatan||'').trim();if(!d||!k||d===k)throw new Error('Akun asal dan tujuan harus berbeda.');if(!isFinite(a)||a<=0)throw new Error('Nominal transfer tidak valid.');ensureTransferSheet().appendRow(['TRF'+Date.now().toString().slice(-8),t,d,k,a,c,new Date()]);return getAccountData()}
function saveBudget(b){const bulan=String(b.bulan||''),kat=String(b.kategori||''),a=Number(b.nominal);if(!/^\d{4}-\d{2}$/.test(bulan)||!kat||!isFinite(a)||a<=0)throw new Error('Budget tidak valid.');const s=ensureBudgetSheet(),d=s.getDataRange().getValues();for(let i=1;i<d.length;i++)if(String(d[i][0])===bulan&&String(d[i][1])===kat){s.getRange(i+1,3).setValue(a);return getBudgetData(bulan)}s.appendRow([bulan,kat,a,new Date()]);return getBudgetData(bulan)}
function reconcileAccount(b){const account=String(b.akun||'').trim(),actual=Number(b.saldoAktual);if(!account||!isFinite(actual)||actual<0)throw new Error('Akun dan saldo aktual wajib valid.');const current=getAccountData().find(x=>x.nama.toLowerCase()===account.toLowerCase());if(!current)throw new Error('Akun tidak ditemukan.');const diff=Math.round((actual-current.saldo)*100)/100;if(diff===0)return{difference:0,message:'Saldo sudah sesuai.'};const s=ensureFinanceSheet(),jenis=diff>0?'Pemasukan':'Pengeluaran',nominal=Math.abs(diff);s.appendRow(['FIN'+Date.now().toString().slice(-9),normalizeFinanceDate(b.tanggal),jenis,'Penyesuaian Saldo',String(b.catatan||'Rekonsiliasi saldo '+account),nominal,account,new Date()]);return{difference:diff,message:'Saldo berhasil disesuaikan.',account:getAccountData().find(x=>x.nama.toLowerCase()===account.toLowerCase())}}
function getAccountData(){const s=ensureAccountSheet(),d=s.getDataRange().getValues(),map={};for(let i=1;i<d.length;i++){if(String(d[i][3])==='false')continue;const n=String(d[i][1]||'').trim();if(!n)continue;const key=n.toLowerCase();if(!map[key])map[key]={id:String(d[i][0]),nama:n,saldoAwal:0,saldo:0};map[key].saldoAwal+=Number(d[i][2])||0;map[key].saldo=map[key].saldoAwal}const out=Object.keys(map).map(k=>map[k]);const t=ensureTransferSheet().getDataRange().getValues();for(let i=1;i<t.length;i++){const a=Number(t[i][4])||0;out.forEach(x=>{if(x.nama.toLowerCase()===String(t[i][2]).trim().toLowerCase())x.saldo-=a;if(x.nama.toLowerCase()===String(t[i][3]).trim().toLowerCase())x.saldo+=a})}const f=ensureFinanceSheet().getDataRange().getValues();for(let i=1;i<f.length;i++){const a=Number(f[i][5])||0;out.forEach(x=>{if(x.nama.toLowerCase()===String(f[i][6]).trim().toLowerCase())x.saldo+=String(f[i][2])==='Pemasukan'?a:-a})}return out}
function getBudgetData(month){const s=ensureBudgetSheet(),d=s.getDataRange().getValues(),out=[];for(let i=1;i<d.length;i++)if(String(d[i][0])===String(month))out.push({kategori:String(d[i][1]),budget:Number(d[i][2])||0});return out}
function getFinanceData(month){const target=/^\d{4}-\d{2}$/.test(String(month||''))?String(month):Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyy-MM'),s=ensureFinanceSheet(),d=s.getDataRange().getValues();let income=0,expense=0,rows=[],categories={},daily={};for(let i=1;i<d.length;i++){const r=d[i],tanggal=normalizeFinanceDate(r[1]);if(tanggal.slice(0,7)!==target)continue;const a=Number(r[5])||0,j=String(r[2]);if(j==='Pemasukan')income+=a;else{expense+=a;categories[String(r[3]||'Lainnya')]=(categories[String(r[3]||'Lainnya')]||0)+a;daily[tanggal]=(daily[tanggal]||0)+a}rows.push({id:String(r[0]),tanggal,jenis:j,kategori:String(r[3]||'Lainnya'),keterangan:String(r[4]||''),nominal:a,metode:String(r[6]||'Cash')})}rows.reverse();const cat=Object.keys(categories).map(k=>({kategori:k,nominal:categories[k]})).sort((a,b)=>b.nominal-a.nominal);const days=Object.keys(daily).sort().map(k=>({tanggal:k,nominal:daily[k]}));const prev=new Date(target+'-01T12:00:00');prev.setMonth(prev.getMonth()-1);const prevMonth=Utilities.formatDate(prev,Session.getScriptTimeZone(),'yyyy-MM');const prevData=getFinanceTotals(prevMonth);return{currency:'KHR',month:target,summary:{income,expense,balance:income-expense,count:rows.length},categories:cat,daily:days,accounts:getAccountData(),budgets:getBudgetData(target),comparison:{previousMonth:prevMonth,previousExpense:prevData.expense,expenseChange:prevData.expense?Math.round((expense-prevData.expense)/prevData.expense*1000)/10:null},transactions:rows}}
function getFinanceTotals(month){const s=ensureFinanceSheet(),d=s.getDataRange().getValues();let income=0,expense=0;for(let i=1;i<d.length;i++){const date=normalizeFinanceDate(d[i][1]);if(date.slice(0,7)!==month)continue;const a=Number(d[i][5])||0;if(String(d[i][2])==='Pemasukan')income+=a;else expense+=a}return{income,expense,balance:income-expense}}
function exportFinanceData(month){const target=/^\d{4}-\d{2}$/.test(String(month||''))?String(month):Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyy-MM');const rows=getFinanceData(target).transactions;const csv=[['Tanggal','Jenis','Kategori','Keterangan','Nominal KHR','Akun'],...rows.map(r=>[r.tanggal,r.jenis,r.kategori,r.keterangan,r.nominal,r.metode])].map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n');return{filename:'keuangan-'+target+'.csv',csv}}
