(function(){
  'use strict';
  const money=(v,c)=>c==='USD'?`$${Number(v||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`:`៛ ${Math.round(Number(v||0)).toLocaleString('id-ID')}`;
  const req=async(action,payload={},method='GET')=>{const url=new URL(API_URL),token=typeof getAuthToken==='function'?getAuthToken():'';const opt={method,mode:'cors',cache:'no-store'};if(method==='GET'){url.searchParams.set('action',action);url.searchParams.set('token',token);Object.entries(payload).forEach(([k,v])=>url.searchParams.set(k,v))}else{opt.headers={'Content-Type':'text/plain;charset=utf-8'};opt.body=JSON.stringify({action,...payload,token})}const r=await fetch(url,opt);if(!r.ok)throw new Error(`Server HTTP ${r.status}`);const j=await r.json();if(!j.ok)throw new Error(j.error||'Finance API error');return j.data};
  const today=()=>{const d=new Date(),x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
  const esc=v=>typeof escapeHtml==='function'?escapeHtml(v):String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
  let accounts=[],history=[];
  function inject(){
    const host=document.getElementById('tab-finance');if(!host||document.getElementById('currency-module'))return;
    Array.from(host.children).forEach(el=>el.style.display='none');
    const wrap=document.createElement('div');wrap.id='currency-module';
    wrap.innerHTML=`<style>
      #currency-module{padding-bottom:28px}.v2-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:16px}.v2-head h2{margin:0}.v2-head p{margin:5px 0 0;opacity:.72}.v2-tools{display:flex;gap:8px;align-items:end}.v2-month{width:150px}.v2-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:18px}.v2-card{padding:16px;border:1px solid rgba(127,127,127,.2);border-radius:14px;background:var(--panel-bg,#fff);box-shadow:0 4px 14px rgba(0,0,0,.05)}.v2-card span{display:block;font-size:.82rem;opacity:.7}.v2-card strong{display:block;margin-top:7px;font-size:1.25rem}.v2-accounts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-bottom:18px}.v2-account{padding:16px;border-radius:14px;border:1px solid rgba(127,127,127,.2);background:var(--panel-bg,#fff)}.v2-account h3{margin:0 0 12px}.v2-line{display:flex;justify-content:space-between;padding:5px 0}.v2-layout{display:grid;grid-template-columns:1fr 1.35fr;gap:16px;margin-bottom:16px}.v2-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.v2-wide{grid-column:1/-1}.v2-table{overflow:auto}.v2-table table{width:100%;border-collapse:collapse}.v2-table th,.v2-table td{padding:9px;border-bottom:1px solid rgba(127,127,127,.15);text-align:left;white-space:nowrap}.v2-muted{opacity:.65}.v2-ok{color:#087443}.v2-error{color:#b42318}.v2-note{font-size:.85rem;opacity:.7;margin-top:10px}.v2-disabled{opacity:.65}.v2-disabled input,.v2-disabled select{background:#f5f5f5}@media(max-width:900px){.v2-summary,.v2-accounts,.v2-layout{grid-template-columns:1fr}.v2-form{grid-template-columns:1fr}}
    </style>
    <div class="v2-head"><div><h2>💰 Keuangan Pribadi</h2><p>Dashboard utama · ABA Bank, Wing, ACLEDA · USD & KHR</p></div><div class="v2-tools"><div><label class="form-label">Bulan</label><input id="v2-month" class="form-control v2-month" type="month"></div><button id="v2-refresh" class="btn btn-outline btn-sm" type="button">↻ Refresh</button></div></div>
    <div class="v2-summary"><div class="v2-card"><span>Total USD</span><strong id="v2-total-usd">$0.00</strong></div><div class="v2-card"><span>Total KHR</span><strong id="v2-total-khr">៛ 0</strong></div><div class="v2-card"><span>Pengeluaran bulan ini</span><strong id="v2-month-expense">-</strong></div><div class="v2-card"><span>Jumlah konversi</span><strong id="v2-conv-count">0</strong></div></div>
    <div class="finance-section-title"><h3>🏦 Saldo Rekening</h3><span>Saldo aktual per rekening dan mata uang</span></div><div id="v2-accounts" class="v2-accounts"></div>
    <div class="v2-layout"><div class="panel"><div class="panel-header"><span>💱 Konversi USD ↔ KHR</span><span class="v2-muted">Kurs terakhir: <b id="v2-last-rate">-</b></span></div><div class="v2-form"><div class="form-group"><label class="form-label">Tanggal</label><input id="v2-date" class="form-control" type="date"></div><div class="form-group"><label class="form-label">Akun</label><select id="v2-account" class="form-control"></select></div><div class="form-group"><label class="form-label">Dari</label><select id="v2-from" class="form-control"><option value="USD">USD — $ Dollar</option><option value="KHR">KHR — ៛ Riel</option></select></div><div class="form-group"><label class="form-label">Ke</label><select id="v2-to" class="form-control"><option value="KHR">KHR — ៛ Riel</option><option value="USD">USD — $ Dollar</option></select></div><div class="form-group"><label class="form-label">Jumlah</label><input id="v2-amount" class="form-control" type="number" min="0.01" step="0.01" placeholder="100"></div><div class="form-group"><label class="form-label">Kurs (៛ per $1)</label><input id="v2-rate" class="form-control" type="number" min="0.01" step="0.01" placeholder="4120"></div><div class="v2-card v2-wide"><span>Hasil Konversi</span><strong id="v2-result">-</strong></div><div class="form-group v2-wide"><label class="form-label">Catatan</label><input id="v2-note" class="form-control" placeholder="Contoh: Tukar uang makan di ABA"></div><button id="v2-save-conv" class="btn btn-primary v2-wide" type="button">⇄ Simpan Konversi</button></div><div id="v2-conv-msg" class="v2-note"></div></div>
    <div class="panel"><div class="panel-header"><span>📜 Riwayat Konversi</span></div><div id="v2-history" class="v2-table"></div></div></div>
    <div class="v2-layout"><div class="panel v2-disabled"><div class="panel-header"><span>📝 Catat Transaksi Harian</span><span class="v2-muted">Tahap berikutnya</span></div><p class="v2-note">Mesin transaksi lama sengaja disembunyikan agar tidak lagi menulis ke Sheet lama. Setelah router Apps Script disatukan, bagian ini akan menjadi satu-satunya tempat mencatat pemasukan dan pengeluaran USD/KHR.</p><div class="v2-form"><select class="form-control" disabled><option>Pengeluaran</option></select><select class="form-control" disabled><option>ABA Bank</option></select><input class="form-control" disabled placeholder="Nominal"><select class="form-control" disabled><option>KHR</option></select><input class="form-control v2-wide" disabled placeholder="Keterangan"><button class="btn btn-success v2-wide" disabled>Simpan Transaksi</button></div></div><div class="panel"><div class="panel-header"><span>ℹ️ Aturan Saldo</span></div><div class="v2-note">Konversi bukan pengeluaran. Contoh $100 → ៛412.000 hanya memindahkan nilai dari saldo USD ke KHR pada rekening yang sama.</div><div class="v2-note">Saldo awal ABA Bank sebesar $360 tetap dipertahankan. Jangan menjalankan setup database lagi karena itu akan mengosongkan saldo awal.</div></div></div>`;
    host.appendChild(wrap);bind();
  }
  function render(){
    const tu=accounts.reduce((s,a)=>s+Number(a.usd||0),0),tk=accounts.reduce((s,a)=>s+Number(a.khr||0),0);document.getElementById('v2-total-usd').textContent=money(tu,'USD');document.getElementById('v2-total-khr').textContent=money(tk,'KHR');
    const box=document.getElementById('v2-accounts');box.innerHTML=accounts.map(a=>`<div class="v2-account"><h3>🏦 ${esc(a.nama)}</h3><div class="v2-line"><span>USD</span><strong>${money(a.usd,'USD')}</strong></div><div class="v2-line"><span>KHR</span><strong>${money(a.khr,'KHR')}</strong></div></div>`).join('');
    const opts=accounts.map(a=>`<option value="${esc(a.nama)}">${esc(a.nama)}</option>`).join('');document.getElementById('v2-account').innerHTML=opts;
    document.getElementById('v2-conv-count').textContent=String(history.length);const last=history[0]?.kurs;document.getElementById('v2-last-rate').textContent=last?`៛ ${Number(last).toLocaleString('id-ID')}`:'-';
  }
  function renderHistory(){const box=document.getElementById('v2-history');if(!history.length){box.innerHTML='<div class="empty-cell">Belum ada konversi.</div>';return}box.innerHTML=`<table><thead><tr><th>Tanggal</th><th>Akun</th><th>Konversi</th><th>Kurs</th><th>Hasil</th><th>Catatan</th></tr></thead><tbody>${history.map(r=>`<tr><td>${esc(r.tanggal)}</td><td>${esc(r.akun)}</td><td>${money(r.nominalDari,r.dari)} → ${esc(r.ke)}</td><td>៛ ${Number(r.kurs||0).toLocaleString('id-ID')}</td><td>${money(r.nominalKe,r.ke)}</td><td>${esc(r.catatan||'-')}</td></tr>`).join('')}</tbody></table>`;}
  function updateResult(){const f=document.getElementById('v2-from').value,t=document.getElementById('v2-to').value,a=Number(document.getElementById('v2-amount').value)||0,r=Number(document.getElementById('v2-rate').value)||0;document.getElementById('v2-result').textContent=a&&r?money(f==='USD'?a*r:a/r,t):'-';}
  async function load(){try{const [a,h]=await Promise.all([req('getCurrencyAccounts'),req('getCurrencyConversions',{limit:100})]);accounts=a.accounts||a||[];history=h.rows||[];render();renderHistory();const r=h.lastRate;if(r&&!document.getElementById('v2-rate').value)document.getElementById('v2-rate').value=r;updateResult()}catch(e){document.getElementById('v2-accounts').innerHTML=`<div class="v2-error">${esc(e.message)}</div>`}}
  function bind(){const d=document.getElementById('v2-date');d.value=today();const month=document.getElementById('v2-month');month.value=today().slice(0,7);document.getElementById('v2-refresh').onclick=load;['v2-from','v2-to','v2-amount','v2-rate'].forEach(id=>document.getElementById(id).addEventListener('input',()=>{if(document.getElementById('v2-from').value===document.getElementById('v2-to').value)document.getElementById('v2-to').value=document.getElementById('v2-from').value==='USD'?'KHR':'USD';updateResult()}));document.getElementById('v2-save-conv').onclick=async()=>{const msg=document.getElementById('v2-conv-msg');const p={tanggal:d.value,akun:document.getElementById('v2-account').value,dari:document.getElementById('v2-from').value,ke:document.getElementById('v2-to').value,nominalDari:Number(document.getElementById('v2-amount').value),kurs:Number(document.getElementById('v2-rate').value),catatan:document.getElementById('v2-note').value.trim()};try{const x=await req('saveCurrencyConversion',p,'POST');msg.className='v2-ok';msg.textContent=`Konversi berhasil: ${money(x.conversion.nominalDari,p.dari)} → ${money(x.conversion.nominalKe,p.ke)}`;document.getElementById('v2-amount').value='';document.getElementById('v2-note').value='';await load()}catch(e){msg.className='v2-error';msg.textContent=e.message}};setTimeout(load,250)}
  window.loadCurrency=load;
  if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',inject,{once:true});else inject();
})();
