const financeState={transactions:[],filterMonth:new Date().toISOString().slice(0,7)};
const financeMoney=v=>Number(v||0).toLocaleString('id-ID');
async function financeRequest(action,payload={},method='GET'){const url=new URL(API_URL);const opt={method,mode:'cors',cache:'no-store'};if(method==='GET'){url.searchParams.set('action',action);Object.entries(payload).forEach(([k,v])=>url.searchParams.set(k,v));}else{opt.headers={'Content-Type':'text/plain;charset=utf-8'};opt.body=JSON.stringify({action,...payload});}const r=await fetch(url,opt);if(!r.ok)throw new Error(`Server HTTP ${r.status}`);const j=await r.json();if(!j.ok)throw new Error(j.error||'Finance API error');return j.data;}
function financeMonth(){return $('finance-month')?.value||financeState.filterMonth;}
function renderFinanceSummary(s){$('finance-income').textContent=`៛ ${financeMoney(s.income)}`;$('finance-expense').textContent=`៛ ${financeMoney(s.expense)}`;$('finance-balance').textContent=`៛ ${financeMoney(s.balance)}`;$('finance-count').textContent=String(s.count||0);}
function renderFinanceTransactions(rows){const body=$('finance-table-body');if(!body)return;if(!rows?.length){body.innerHTML='<tr><td colspan="7" class="empty-cell">Belum ada catatan keuangan bulan ini.</td></tr>';return;}body.innerHTML=rows.map(x=>`<tr><td>${escapeHtml(x.tanggal)}</td><td><span class="badge ${x.jenis==='Pemasukan'?'badge-paid':'badge-unpaid'}">${escapeHtml(x.jenis)}</span></td><td>${escapeHtml(x.kategori)}</td><td><strong>${escapeHtml(x.keterangan)}</strong></td><td>៛ ${financeMoney(x.nominal)}</td><td>${escapeHtml(x.metode)}</td><td><button class="btn btn-sm btn-danger finance-delete" data-id="${escapeHtml(x.id)}" type="button"><i class="fas fa-trash"></i></button></td></tr>`).join('');}
async function loadFinance(){try{const data=await financeRequest('getFinance',{month:financeMonth()});financeState.transactions=data.transactions||[];renderFinanceSummary(data.summary||{});renderFinanceTransactions(financeState.transactions);}catch(e){$('finance-table-body').innerHTML=`<tr><td colspan="7" class="empty-cell error-text">${escapeHtml(e.message)}</td></tr>`;}}
async function saveFinance(){const tanggal=$('finance-date').value||new Date().toISOString().slice(0,10),jenis=$('finance-type').value,kategori=$('finance-category').value,keterangan=$('finance-note').value.trim(),nominal=Number($('finance-amount').value),metode=$('finance-method').value;if(!keterangan||!nominal||nominal<0) return alert('Keterangan dan nominal wajib diisi.');const b=$('finance-save');setBusy(b,true);try{await financeRequest('saveFinance',{tanggal,jenis,kategori,keterangan,nominal,metode},'POST');$('finance-note').value='';$('finance-amount').value='';$('finance-month').value=tanggal.slice(0,7);financeState.filterMonth=tanggal.slice(0,7);await loadFinance();alert('Catatan keuangan berhasil disimpan.');}catch(e){alert(`Gagal menyimpan: ${e.message}`);}finally{setBusy(b,false,'<i class="fas fa-save"></i> Simpan Catatan');}}
async function deleteFinance(id){if(!confirm('Hapus catatan keuangan ini?'))return;try{await financeRequest('deleteFinance',{id},'POST');await loadFinance();}catch(e){alert(`Gagal menghapus: ${e.message}`);}}
function initFinance(){const d=new Date();const iso=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);if($('finance-date'))$('finance-date').value=iso;if($('finance-month'))$('finance-month').value=financeState.filterMonth;loadFinance();}
document.addEventListener('click',e=>{const b=e.target.closest('.finance-delete');if(b)deleteFinance(b.dataset.id);});