const financeState={transactions:[],filterMonth:new Date().toISOString().slice(0,7)};
const financeMoney=v=>Number(v||0).toLocaleString('id-ID');
async function financeRequest(action,payload={},method='GET'){const url=new URL(API_URL);const opt={method,mode:'cors',cache:'no-store'};if(method==='GET'){url.searchParams.set('action',action);Object.entries(payload).forEach(([k,v])=>url.searchParams.set(k,v))}else{opt.headers={'Content-Type':'text/plain;charset=utf-8'};opt.body=JSON.stringify({action,...payload})}const r=await fetch(url,opt);if(!r.ok)throw new Error(`Server HTTP ${r.status}`);const j=await r.json();if(!j.ok)throw new Error(j.error||'Finance API error');return j.data}
function financeMonth(){return $('finance-month')?.value||financeState.filterMonth}
function renderFinanceSummary(s){$('finance-income').textContent=`៛ ${financeMoney(s.income)}`;$('finance-expense').textContent=`៛ ${financeMoney(s.expense)}`;$('finance-balance').textContent=`៛ ${financeMoney(s.balance)}`;$('finance-count').textContent=String(s.count||0)}
function renderFinanceTransactions(rows){const body=$('finance-table-body');if(!body)return;if(!rows?.length){body.innerHTML='<tr><td colspan="7" class="empty-cell">Belum ada catatan keuangan bulan ini.</td></tr>';return}body.innerHTML=rows.map(x=>`<tr><td>${escapeHtml(x.tanggal)}</td><td><span class="badge ${x.jenis==='Pemasukan'?'badge-paid':'badge-unpaid'}">${escapeHtml(x.jenis)}</span></td><td>${escapeHtml(x.kategori)}</td><td><strong>${escapeHtml(x.keterangan)}</strong></td><td>៛ ${financeMoney(x.nominal)}</td><td>${escapeHtml(x.metode)}</td><td><button class="btn btn-sm btn-danger finance-delete" data-id="${escapeHtml(x.id)}"><i class="fas fa-trash"></i></button></td></tr>`).join('')}
function renderFinanceExtras(data){const accounts=$('finance-accounts');if(accounts)accounts.innerHTML=(data.accounts||[]).map(a=>`<div class="account-card"><span>${escapeHtml(a.nama)}</span><strong>៛ ${financeMoney(a.saldo)}</strong></div>`).join('')||'<div class="empty-cell">Belum ada akun.</div>';const cats=$('finance-categories');if(cats)cats.innerHTML=(data.categories||[]).map(c=>`<div class="category-row"><span>${escapeHtml(c.kategori)}</span><strong>៛ ${financeMoney(c.nominal)}</strong></div>`).join('')||'<div class="empty-cell">Belum ada pengeluaran.</div>';const budgets=$('finance-budgets');if(budgets){const map={};(data.categories||[]).forEach(c=>map[c.kategori]=c.nominal);budgets.innerHTML=(data.budgets||[]).map(b=>{const used=map[b.kategori]||0,p=Math.min(100,Math.round(used/b.budget*100));return `<div class="budget-row"><div><span>${escapeHtml(b.kategori)}</span><strong>៛ ${financeMoney(used)} / ៛ ${financeMoney(b.budget)}</strong></div><div class="budget-track"><i style="width:${p}%"></i></div><small>${p}% terpakai</small></div>`}).join('')||'<div class="empty-cell">Belum ada budget bulan ini.</div>'}}
async function loadFinance(){try{const data=await financeRequest('getFinance',{month:financeMonth()});financeState.transactions=data.transactions||[];renderFinanceSummary(data.summary||{});renderFinanceTransactions(financeState.transactions);renderFinanceExtras(data);populateAccountOptions(data.accounts||[])}catch(e){$('finance-table-body').innerHTML=`<tr><td colspan="7" class="empty-cell error-text">${escapeHtml(e.message)}</td></tr>`}}
function populateAccountOptions(accounts){['finance-method','transfer-from','transfer-to'].forEach(id=>{const el=$(id);if(!el)return;const current=el.value;el.innerHTML=accounts.map(a=>`<option value="${escapeHtml(a.nama)}">${escapeHtml(a.nama)}</option>`).join('');if([...el.options].some(o=>o.value===current))el.value=current})}
async function saveFinance(){const tanggal=$('finance-date').value||new Date().toISOString().slice(0,10),jenis=$('finance-type').value,kategori=$('finance-category').value,keterangan=$('finance-note').value.trim(),nominal=Number($('finance-amount').value),metode=$('finance-method').value;if(!keterangan||!nominal||nominal<0)return alert('Keterangan dan nominal wajib diisi.');const b=$('finance-save');setBusy(b,true);try{await financeRequest('saveFinance',{tanggal,jenis,kategori,keterangan,nominal,metode},'POST');$('finance-note').value='';$('finance-amount').value='';$('finance-month').value=tanggal.slice(0,7);financeState.filterMonth=tanggal.slice(0,7);await loadFinance();alert('Catatan keuangan berhasil disimpan.')}catch(e){alert(`Gagal menyimpan: ${e.message}`)}finally{setBusy(b,false,'<i class="fas fa-save"></i> Simpan Catatan')}}
async function deleteFinance(id){if(!confirm('Hapus catatan keuangan ini?'))return;try{await financeRequest('deleteFinance',{id},'POST');await loadFinance()}catch(e){alert(`Gagal: ${e.message}`)}}
async function saveAccount(){const nama=$('account-name').value.trim(),saldo=Number($('account-opening').value)||0;if(!nama)return alert('Nama akun wajib diisi.');try{await financeRequest('saveAccount',{nama,saldoAwal:saldo},'POST');$('account-name').value='';$('account-opening').value='';await loadFinance();alert('Akun berhasil ditambahkan.')}catch(e){alert(`Gagal: ${e.message}`)}}
async function saveTransfer(){const nominal=Number($('transfer-amount').value)||0;if(!nominal)return alert('Nominal transfer wajib diisi.');try{await financeRequest('saveTransfer',{tanggal:$('transfer-date').value||new Date().toISOString().slice(0,10),dari:$('transfer-from').value,ke:$('transfer-to').value,nominal,catatan:$('transfer-note').value.trim()},'POST');$('transfer-amount').value='';$('transfer-note').value='';await loadFinance();alert('Transfer berhasil dicatat.')}catch(e){alert(`Gagal: ${e.message}`)}}
async function saveBudget(){const nominal=Number($('budget-amount').value)||0;if(!nominal)return alert('Nominal budget wajib diisi.');try{await financeRequest('saveBudget',{bulan:financeMonth(),kategori:$('budget-category').value,nominal},'POST');$('budget-amount').value='';await loadFinance();alert('Budget berhasil disimpan.')}catch(e){alert(`Gagal: ${e.message}`)}}
function initFinance(){const d=new Date(),iso=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);if($('finance-date'))$('finance-date').value=iso;if($('transfer-date'))$('transfer-date').value=iso;if($('finance-month'))$('finance-month').value=financeState.filterMonth;loadFinance()}
document.addEventListener('click',e=>{const b=e.target.closest('.finance-delete');if(b)deleteFinance(b.dataset.id)})